### ISSUE TITLE
Boards aren't loading properly

### ISSUE THREAD

**Issue by ThePolarCat** [per1234/Arduino-AVRISPmkII-fix#2]
avr/boardes.txt is blank.

Boards Manager method installs but Arduino only show a drop down list with no items.

**Comment by per1234** [comment]
Hi @ThePolarCat. Thanks for your report.

>avr/boardes.txt is blank.

That is intended. Even though it is packaged as an Arduino boards platform, this project consists solely of a custom ISP programmer definition for the AVRISP mkII. The `boards.txt` file is required for the Arduino development software to recognize it as a boards platform.

>Arduino only show a drop down list with no items. 

Unfortunately, this project was a casualty of an otherwise very helpful change to the Arduino IDE made in the 1.8.13 release:

https://github.com/arduino/Arduino/pull/9900

The support for distributing custom programmer definitions as boards platforms required by this project is only available in previous versions of the Arduino IDE, so it can only be used with Arduino IDE 1.8.12 and older.

If you want to try it for some reason, you can get the old IDE versions here:

https://www.arduino.cc/en/software/OldSoftwareReleases#arduino-18x

However, it is generally recommended to use the modern Arduino IDE 1.8.19 in order to benefit from all the advancements that were made over the years since that release.

The excellent news is that this workaround should no longer be needed if you use a modern version of the Arduino boards platforms, since my testing indicates the problem does not occur when using the AVRDUDE 6.3.0 release that is now in common usage.

I was remiss in not documenting these facts in the project's readme. I have now done so to save others from such confusion.

If you are still having trouble with your AVRISP mkII or with this platform, please feel free to post the details over on the Arduino Forum. I'm sure we'll be able to help you out over there:

https://forum.arduino.cc/
